name: Container image build

on:
  repository_dispatch:
    types: [trigger_workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Fetch release'
      uses: robinraju/release-downloader@v1
      with: 
        repository: danielmilanov/challenge
        latest: true
        tarBall: true
        fileName: '*'

    - name: 'Extract release'
      run: | 
        tar xzf *.tar.gz;
        mv danielmilanov-challenge-*/* .;
        chmod +x challenge

    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v3
      
    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 'Build'
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: milanovdan175/challenge:latest
